#include "8051_instruction_set.h"

struct a8051InstructionInfo A8051_Instruction_Set[] = {
    {0x00, "nop", 1, 0, {OPERAND_NONE}},
    {0x01, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0x02, "ljmp", 3, 1, {OPERAND_ADDR_16}},
    {0x03, "rr", 1, 1, {OPERAND_A}},
    {0x04, "inc", 1, 1, {OPERAND_A}},
    {0x05, "inc", 2, 1, {OPERAND_ADDR_DIRECT}},
    {0x06, "inc", 1, 1, {OPERAND_IND_R}},
    {0x07, "inc", 1, 1, {OPERAND_IND_R}},
    {0x08, "inc", 1, 1, {OPERAND_R}},
    {0x09, "inc", 1, 1, {OPERAND_R}},
    {0x0a, "inc", 1, 1, {OPERAND_R}},
    {0x0b, "inc", 1, 1, {OPERAND_R}},
    {0x0c, "inc", 1, 1, {OPERAND_R}},
    {0x0d, "inc", 1, 1, {OPERAND_R}},
    {0x0e, "inc", 1, 1, {OPERAND_R}},
    {0x0f, "inc", 1, 1, {OPERAND_R}},
    {0x10, "jbc", 3, 2, {OPERAND_ADDR_BIT, OPERAND_ADDR_RELATIVE}},
    {0x11, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0x12, "lcall", 3, 1, {OPERAND_ADDR_16}},
    {0x13, "rrc", 1, 1, {OPERAND_A}},
    {0x14, "dec", 1, 1, {OPERAND_A}},
    {0x15, "dec", 2, 1, {OPERAND_ADDR_DIRECT}},
    {0x16, "dec", 1, 1, {OPERAND_IND_R}},
    {0x17, "dec", 1, 1, {OPERAND_IND_R}},
    {0x18, "dec", 1, 1, {OPERAND_R}},
    {0x19, "dec", 1, 1, {OPERAND_R}},
    {0x1a, "dec", 1, 1, {OPERAND_R}},
    {0x1b, "dec", 1, 1, {OPERAND_R}},
    {0x1c, "dec", 1, 1, {OPERAND_R}},
    {0x1d, "dec", 1, 1, {OPERAND_R}},
    {0x1e, "dec", 1, 1, {OPERAND_R}},
    {0x1f, "dec", 1, 1, {OPERAND_R}},
    {0x20, "jb", 3, 2, {OPERAND_ADDR_BIT, OPERAND_ADDR_RELATIVE}},
    {0x21, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0x22, "ret", 1, 0, {OPERAND_NONE}},
    {0x23, "rl", 1, 1, {OPERAND_A}},
    {0x24, "add", 2, 2, {OPERAND_A, OPERAND_IMMED}},
    {0x25, "add", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0x26, "add", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x27, "add", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x28, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x29, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x2a, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x2b, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x2c, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x2d, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x2e, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x2f, "add", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x30, "jnb", 3, 2, {OPERAND_ADDR_BIT, OPERAND_ADDR_RELATIVE}},
    {0x31, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0x32, "reti", 1, 0, {OPERAND_NONE}},
    {0x33, "rlc", 1, 1, {OPERAND_A}},
    {0x34, "addc", 2, 2, {OPERAND_A, OPERAND_IMMED}},
    {0x35, "addc", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0x36, "addc", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x37, "addc", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x38, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x39, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x3a, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x3b, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x3c, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x3d, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x3e, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x3f, "addc", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x40, "jc", 2, 1, {OPERAND_ADDR_RELATIVE}},
    {0x41, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0x42, "orl", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_A}},
    {0x43, "orl", 3, 2, {OPERAND_ADDR_DIRECT, OPERAND_IMMED}},
    {0x44, "orl", 2, 2, {OPERAND_A, OPERAND_IMMED}},
    {0x45, "orl", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0x46, "orl", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x47, "orl", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x48, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x49, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x4a, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x4b, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x4c, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x4d, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x4e, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x4f, "orl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x50, "jnc", 2, 1, {OPERAND_ADDR_RELATIVE}},
    {0x51, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0x52, "anl", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_A}},
    {0x53, "anl", 3, 2, {OPERAND_ADDR_DIRECT, OPERAND_IMMED}},
    {0x54, "anl", 2, 2, {OPERAND_A, OPERAND_IMMED}},
    {0x55, "anl", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0x56, "anl", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x57, "anl", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x58, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x59, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x5a, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x5b, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x5c, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x5d, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x5e, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x5f, "anl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x60, "jz", 2, 1, {OPERAND_ADDR_RELATIVE}},
    {0x61, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0x62, "xrl", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_A}},
    {0x63, "xrl", 3, 2, {OPERAND_ADDR_DIRECT, OPERAND_IMMED}},
    {0x64, "xrl", 2, 2, {OPERAND_A, OPERAND_IMMED}},
    {0x65, "xrl", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0x66, "xrl", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x67, "xrl", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x68, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x69, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x6a, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x6b, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x6c, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x6d, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x6e, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x6f, "xrl", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x70, "jnz", 2, 1, {OPERAND_ADDR_RELATIVE}},
    {0x71, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0x72, "orl", 2, 2, {OPERAND_C, OPERAND_ADDR_BIT}},
    {0x73, "jmp", 1, 1, {OPERAND_IND_A_DPTR}},
    {0x74, "mov", 2, 2, {OPERAND_A, OPERAND_IMMED}},
    {0x75, "mov", 3, 2, {OPERAND_ADDR_DIRECT, OPERAND_IMMED}},
    {0x76, "mov", 2, 2, {OPERAND_IND_R, OPERAND_IMMED}},
    {0x77, "mov", 2, 2, {OPERAND_IND_R, OPERAND_IMMED}},
    {0x78, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x79, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x7a, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x7b, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x7c, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x7d, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x7e, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x7f, "mov", 2, 2, {OPERAND_R, OPERAND_IMMED}},
    {0x80, "sjmp", 2, 1, {OPERAND_ADDR_RELATIVE}},
    {0x81, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0x82, "anl", 2, 2, {OPERAND_C, OPERAND_ADDR_BIT}},
    {0x83, "movc", 1, 2, {OPERAND_A, OPERAND_IND_A_PC}},
    {0x84, "div", 1, 1, {OPERAND_AB}},
    {0x85, "mov", 3, 2, {OPERAND_ADDR_DIRECT_DST, OPERAND_ADDR_DIRECT_SRC}},
    {0x86, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_IND_R}},
    {0x87, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_IND_R}},
    {0x88, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x89, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x8a, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x8b, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x8c, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x8d, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x8e, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x8f, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_R}},
    {0x90, "mov", 3, 2, {OPERAND_DPTR, OPERAND_IMMED_16}},
    {0x91, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0x92, "mov", 2, 2, {OPERAND_ADDR_BIT, OPERAND_C}},
    {0x93, "movc", 1, 2, {OPERAND_A, OPERAND_IND_A_DPTR}},
    {0x94, "subb", 2, 2, {OPERAND_A, OPERAND_IMMED}},
    {0x95, "subb", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0x96, "subb", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x97, "subb", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0x98, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x99, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x9a, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x9b, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x9c, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x9d, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x9e, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0x9f, "subb", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xa0, "orl", 2, 2, {OPERAND_C, OPERAND_ADDR_NOT_BIT}},
    {0xa1, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0xa2, "mov", 2, 2, {OPERAND_C, OPERAND_ADDR_BIT}},
    {0xa3, "inc", 1, 1, {OPERAND_DPTR}},
    {0xa4, "mul", 1, 1, {OPERAND_AB}},
    {0xa5, "resrvd", 1, 0, {OPERAND_NONE}},
    {0xa6, "mov", 2, 2, {OPERAND_IND_R, OPERAND_ADDR_DIRECT}},
    {0xa7, "mov", 2, 2, {OPERAND_IND_R, OPERAND_ADDR_DIRECT}},
    {0xa8, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xa9, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xaa, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xab, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xac, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xad, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xae, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xaf, "mov", 2, 2, {OPERAND_R, OPERAND_ADDR_DIRECT}},
    {0xb0, "anl", 2, 2, {OPERAND_C, OPERAND_ADDR_NOT_BIT}},
    {0xb1, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0xb2, "cpl", 2, 1, {OPERAND_ADDR_BIT}},
    {0xb3, "cpl", 1, 1, {OPERAND_C}},
    {0xb4, "cjne", 3, 3, {OPERAND_A, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xb5, "cjne", 3, 3, {OPERAND_A, OPERAND_ADDR_DIRECT, OPERAND_ADDR_RELATIVE}},
    {0xb6, "cjne", 3, 3, {OPERAND_IND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xb7, "cjne", 3, 3, {OPERAND_IND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xb8, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xb9, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xba, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xbb, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xbc, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xbd, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xbe, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xbf, "cjne", 3, 3, {OPERAND_R, OPERAND_IMMED, OPERAND_ADDR_RELATIVE}},
    {0xc0, "push", 2, 1, {OPERAND_ADDR_DIRECT}},
    {0xc1, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0xc2, "clr", 2, 1, {OPERAND_ADDR_BIT}},
    {0xc3, "clr", 1, 1, {OPERAND_C}},
    {0xc4, "swap", 1, 1, {OPERAND_A}},
    {0xc5, "xch", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0xc6, "xch", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xc7, "xch", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xc8, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xc9, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xca, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xcb, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xcc, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xcd, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xce, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xcf, "xch", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xd0, "pop", 2, 1, {OPERAND_ADDR_DIRECT}},
    {0xd1, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0xd2, "setb", 2, 1, {OPERAND_ADDR_BIT}},
    {0xd3, "setb", 1, 1, {OPERAND_C}},
    {0xd4, "da", 1, 1, {OPERAND_A}},
    {0xd5, "djnz", 3, 2, {OPERAND_ADDR_DIRECT, OPERAND_ADDR_RELATIVE}},
    {0xd6, "xchd", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xd7, "xchd", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xd8, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xd9, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xda, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xdb, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xdc, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xdd, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xde, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xdf, "djnz", 2, 2, {OPERAND_R, OPERAND_ADDR_RELATIVE}},
    {0xe0, "movx", 1, 2, {OPERAND_A, OPERAND_IND_DPTR}},
    {0xe1, "ajmp", 2, 1, {OPERAND_ADDR_11}},
    {0xe2, "movx", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xe3, "movx", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xe4, "clr", 1, 1, {OPERAND_A}},
    {0xe5, "mov", 2, 2, {OPERAND_A, OPERAND_ADDR_DIRECT}},
    {0xe6, "mov", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xe7, "mov", 1, 2, {OPERAND_A, OPERAND_IND_R}},
    {0xe8, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xe9, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xea, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xeb, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xec, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xed, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xee, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xef, "mov", 1, 2, {OPERAND_A, OPERAND_R}},
    {0xf0, "movx", 1, 2, {OPERAND_IND_DPTR, OPERAND_A}},
    {0xf1, "acall", 2, 1, {OPERAND_ADDR_11}},
    {0xf2, "movx", 1, 2, {OPERAND_IND_R, OPERAND_A}},
    {0xf3, "movx", 1, 2, {OPERAND_IND_R, OPERAND_A}},
    {0xf4, "cpl", 1, 1, {OPERAND_A}},
    {0xf5, "mov", 2, 2, {OPERAND_ADDR_DIRECT, OPERAND_A}},
    {0xf6, "mov", 1, 2, {OPERAND_IND_R, OPERAND_A}},
    {0xf7, "mov", 1, 2, {OPERAND_IND_R, OPERAND_A}},
    {0xf8, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0xf9, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0xfa, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0xfb, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0xfc, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0xfd, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0xfe, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0xff, "mov", 1, 2, {OPERAND_R, OPERAND_A}},
    {0x00, ".db", 1, 1, {OPERAND_IMMED}},
};

/* Total number of 8051 instructions */
int A8051_TOTAL_INSTRUCTIONS = (sizeof(A8051_Instruction_Set)/sizeof(A8051_Instruction_Set[0]));

